language: python
python:
    - "2.7"
notifications:
    irc:
        - "chat.freenode.net#unary"
    email:
        - "admin@unary.ca"
env:
    - PYTHONPATH=./
install:
    - pip install tox
    - pip install coveralls
script:
    - python setup.py test
after_success:
    - coveralls
